name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: ['Debug', 'Release']

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (cached)
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libsdl2-dev libgtk-3-dev
    - name: Compile ${{ matrix.build_type }} build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
        cmake --build .

  #build-windows:
  #  runs-on: windows-2019
  #
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Compile release build
  #    shell: cmd
  #    run: |
  #      mkdir build-release
  #      cd build-release
  #      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
  #      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -G "Ninja" -DCMAKE_C_COMPILER=cl -DCMAKE_C_COMPILER_FORCED=ON -DCMAKE_CXX_COMPILER=cl -DCMAKE_CXX_COMPILER_FORCED=ON -DCMAKE_BUILD_TYPE=Release ..
  #      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build .
