name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: sudo apt-get install libsdl2-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: build
      run: cmake --build build
    #- name: test
    #  run: cd build && ctest
