name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install libsdl2-dev
    - name: compile debug build
      run: |
        mkdir build-debug
        cd build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build .
    - name: compile release build
      run: |
        mkdir build-release
        cd build-release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
    #- name: test
    #  run: cd build && ctest

  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: compile release build
      run: |
        mkdir build-release
        cd build-release
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
